"""sync backend to db

Revision ID: 1571fdc436ce
Revises: 9d091ed01ec7
Create Date: 2025-06-06 13:48:55.550204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1571fdc436ce'
down_revision = '9d091ed01ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alocacao_recurso_projeto_equipe_id'), 'alocacao_recurso_projeto', ['equipe_id'], unique=False)
    op.create_index(op.f('ix_alocacao_recurso_projeto_status_alocacao_id'), 'alocacao_recurso_projeto', ['status_alocacao_id'], unique=False)
    op.drop_constraint('fk_status_alocacao', 'alocacao_recurso_projeto', type_='foreignkey')
    op.drop_constraint('fk_alocacao_equipe', 'alocacao_recurso_projeto', type_='foreignkey')
    op.create_foreign_key(None, 'alocacao_recurso_projeto', 'equipe', ['equipe_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'alocacao_recurso_projeto', 'status_projeto', ['status_alocacao_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('alocacao_recurso_projeto', 'periodo')
    op.drop_constraint('uq_projeto_interno_nome_secao', 'projeto', type_='unique')
    op.create_index(op.f('ix_projeto_codigo_empresa'), 'projeto', ['codigo_empresa'], unique=True)
    op.create_index(op.f('ix_projeto_secao_id'), 'projeto', ['secao_id'], unique=False)
    op.drop_constraint('fk_projeto_secao', 'projeto', type_='foreignkey')
    op.create_foreign_key(None, 'projeto', 'secao', ['secao_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('recurso', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('secao_jira_project_key_key', 'secao', type_='unique')
    op.drop_index('ix_secao_jira_project_key', table_name='secao')
    op.create_index(op.f('ix_secao_jira_project_key'), 'secao', ['jira_project_key'], unique=True)
    op.alter_column('sincronizacao_jira', 'data_fim',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sincronizacao_jira', 'data_fim',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_secao_jira_project_key'), table_name='secao')
    op.create_index('ix_secao_jira_project_key', 'secao', ['jira_project_key'], unique=False)
    op.create_unique_constraint('secao_jira_project_key_key', 'secao', ['jira_project_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('recurso', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'projeto', type_='foreignkey')
    op.create_foreign_key('fk_projeto_secao', 'projeto', 'secao', ['secao_id'], ['id'])
    op.drop_index(op.f('ix_projeto_secao_id'), table_name='projeto')
    op.drop_index(op.f('ix_projeto_codigo_empresa'), table_name='projeto')
    op.create_unique_constraint('uq_projeto_interno_nome_secao', 'projeto', ['nome', 'secao_id', 'codigo_empresa'], postgresql_nulls_not_distinct=False)
    op.add_column('alocacao_recurso_projeto', sa.Column('periodo', postgresql.TSRANGE(), sa.Computed("tsrange((data_inicio_alocacao)::timestamp without time zone, (COALESCE(data_fim_alocacao, 'infinity'::date))::timestamp without time zone, '[)'::text)", persisted=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alocacao_recurso_projeto', type_='foreignkey')
    op.drop_constraint(None, 'alocacao_recurso_projeto', type_='foreignkey')
    op.create_foreign_key('fk_alocacao_equipe', 'alocacao_recurso_projeto', 'equipe', ['equipe_id'], ['id'])
    op.create_foreign_key('fk_status_alocacao', 'alocacao_recurso_projeto', 'status_projeto', ['status_alocacao_id'], ['id'])
    op.drop_index(op.f('ix_alocacao_recurso_projeto_status_alocacao_id'), table_name='alocacao_recurso_projeto')
    op.drop_index(op.f('ix_alocacao_recurso_projeto_equipe_id'), table_name='alocacao_recurso_projeto')
    # ### end Alembic commands ### 