"""Adiciona esforco estimado e planejado a alocacao

Revision ID: 696b6a4d1edc
Revises: 9d091ed01ec7
Create Date: 2025-07-15 14:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696b6a4d1edc'
down_revision = '9d091ed01ec7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alocacao_recurso_projeto', sa.Column('esforco_estimado', sa.DECIMAL(10, 2), nullable=True))
    op.add_column('alocacao_recurso_projeto', sa.Column('esforco_planejado', sa.DECIMAL(10, 2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alocacao_recurso_projeto', 'esforco_planejado')
    op.drop_column('alocacao_recurso_projeto', 'esforco_estimado')
    # ### end Alembic commands ###
