"""Criação inicial das tabelas

Revision ID: 9d091ed01ec7
Revises: 
Create Date: 2025-05-09 11:27:30.365519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d091ed01ec7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('dim_tempo',
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ano', sa.SmallInteger(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('trimestre', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('nome_dia_semana', sa.String(length=20), nullable=False),
    sa.Column('nome_mes', sa.String(length=20), nullable=False),
    sa.Column('semana_ano', sa.Integer(), nullable=False),
    sa.Column('is_dia_util', sa.Boolean(), nullable=False),
    sa.Column('is_feriado', sa.Boolean(), nullable=False),
    sa.Column('nome_feriado', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('data_id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('secao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('status_projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('ordem_exibicao', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('ordem_exibicao')
    )
    op.create_table('equipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('secao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['secao_id'], ['secao.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secao_id', 'nome', name='uq_equipe_secao_nome')
    )
    op.create_index(op.f('ix_equipe_secao_id'), 'equipe', ['secao_id'], unique=False)
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('codigo_empresa', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('jira_project_key', sa.String(length=100), nullable=True),
    sa.Column('status_projeto', sa.Integer(), nullable=False),
    sa.Column('data_inicio_prevista', sa.Date(), nullable=True),
    sa.Column('data_fim_prevista', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['status_projeto'], ['status_projeto.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projeto_codigo_empresa'), 'projeto', ['codigo_empresa'], unique=True)
    op.create_index(op.f('ix_projeto_jira_project_key'), 'projeto', ['jira_project_key'], unique=True)
    op.create_index(op.f('ix_projeto_status_projeto'), 'projeto', ['status_projeto'], unique=False)
    op.create_table('recurso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipe_principal_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('jira_user_id', sa.String(length=100), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_principal_id'], ['equipe.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurso_email'), 'recurso', ['email'], unique=True)
    op.create_index(op.f('ix_recurso_equipe_principal_id'), 'recurso', ['equipe_principal_id'], unique=False)
    op.create_index(op.f('ix_recurso_jira_user_id'), 'recurso', ['jira_user_id'], unique=True)
    op.create_index(op.f('ix_recurso_matricula'), 'recurso', ['matricula'], unique=True)
    op.create_table('alocacao_recurso_projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio_alocacao', sa.Date(), nullable=False),
    sa.Column('data_fim_alocacao', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.CheckConstraint('data_fim_alocacao IS NULL OR data_fim_alocacao >= data_inicio_alocacao', name='chk_alocacao_datas'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurso_id', 'projeto_id', 'data_inicio_alocacao', name='uq_alocacao_recurso_projeto_data')
    )
    op.create_index(op.f('ix_alocacao_recurso_projeto_projeto_id'), 'alocacao_recurso_projeto', ['projeto_id'], unique=False)
    op.create_index(op.f('ix_alocacao_recurso_projeto_recurso_id'), 'alocacao_recurso_projeto', ['recurso_id'], unique=False)
    op.create_table('horas_disponiveis_rh',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.SmallInteger(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('horas_disponiveis_mes', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.CheckConstraint('horas_disponiveis_mes >= 0', name='chk_horas_disponveis_valor'),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='chk_horas_disponveis_mes'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurso_id', 'ano', 'mes', name='uq_horas_disponveis_recurso_ano_mes')
    )
    op.create_index(op.f('ix_horas_disponiveis_rh_recurso_id'), 'horas_disponiveis_rh', ['recurso_id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'GESTOR', 'RECURSO', name='userrole'), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurso_id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('apontamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jira_worklog_id', sa.String(length=255), nullable=True),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=50), nullable=True),
    sa.Column('data_hora_inicio_trabalho', sa.DateTime(), nullable=True),
    sa.Column('data_apontamento', sa.Date(), nullable=False),
    sa.Column('horas_apontadas', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fonte_apontamento', sa.Enum('JIRA', 'MANUAL', name='fonteapontamento'), nullable=False),
    sa.Column('id_usuario_admin_criador', sa.Integer(), nullable=True),
    sa.Column('data_sincronizacao_jira', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.CheckConstraint('horas_apontadas > 0 AND horas_apontadas <= 24', name='chk_apontamento_horas'),
    sa.ForeignKeyConstraint(['id_usuario_admin_criador'], ['usuario.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apontamento_data_apontamento'), 'apontamento', ['data_apontamento'], unique=False)
    op.create_index(op.f('ix_apontamento_fonte_apontamento'), 'apontamento', ['fonte_apontamento'], unique=False)
    op.create_index(op.f('ix_apontamento_id_usuario_admin_criador'), 'apontamento', ['id_usuario_admin_criador'], unique=False)
    op.create_index(op.f('ix_apontamento_jira_issue_key'), 'apontamento', ['jira_issue_key'], unique=False)
    op.create_index(op.f('ix_apontamento_jira_worklog_id'), 'apontamento', ['jira_worklog_id'], unique=True)
    op.create_index(op.f('ix_apontamento_projeto_id'), 'apontamento', ['projeto_id'], unique=False)
    op.create_index(op.f('ix_apontamento_recurso_id'), 'apontamento', ['recurso_id'], unique=False)
    op.create_table('horas_planejadas_alocacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alocacao_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.SmallInteger(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('horas_planejadas', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.CheckConstraint('horas_planejadas >= 0', name='chk_horas_planejadas_valor'),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='chk_horas_planejadas_mes'),
    sa.ForeignKeyConstraint(['alocacao_id'], ['alocacao_recurso_projeto.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alocacao_id', 'ano', 'mes', name='uq_horas_planejadas_alocacao_ano_mes')
    )
    op.create_index(op.f('ix_horas_planejadas_alocacao_alocacao_id'), 'horas_planejadas_alocacao', ['alocacao_id'], unique=False)
    op.create_table('log_atividade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.Column('tabela_afetada', sa.String(length=100), nullable=True),
    sa.Column('registro_id', sa.String(length=255), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('data_hora', sa.TIMESTAMP(timezone=6), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_atividade_data_hora'), 'log_atividade', ['data_hora'], unique=False)
    op.create_index(op.f('ix_log_atividade_usuario_id'), 'log_atividade', ['usuario_id'], unique=False)
    op.create_table('sincronizacao_jira',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('quantidade_apontamentos_processados', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sincronizacao_jira')
    op.drop_index(op.f('ix_log_atividade_usuario_id'), table_name='log_atividade')
    op.drop_index(op.f('ix_log_atividade_data_hora'), table_name='log_atividade')
    op.drop_table('log_atividade')
    op.drop_index(op.f('ix_horas_planejadas_alocacao_alocacao_id'), table_name='horas_planejadas_alocacao')
    op.drop_table('horas_planejadas_alocacao')
    op.drop_index(op.f('ix_apontamento_recurso_id'), table_name='apontamento')
    op.drop_index(op.f('ix_apontamento_projeto_id'), table_name='apontamento')
    op.drop_index(op.f('ix_apontamento_jira_worklog_id'), table_name='apontamento')
    op.drop_index(op.f('ix_apontamento_jira_issue_key'), table_name='apontamento')
    op.drop_index(op.f('ix_apontamento_id_usuario_admin_criador'), table_name='apontamento')
    op.drop_index(op.f('ix_apontamento_fonte_apontamento'), table_name='apontamento')
    op.drop_index(op.f('ix_apontamento_data_apontamento'), table_name='apontamento')
    op.drop_table('apontamento')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_horas_disponiveis_rh_recurso_id'), table_name='horas_disponiveis_rh')
    op.drop_table('horas_disponiveis_rh')
    op.drop_index(op.f('ix_alocacao_recurso_projeto_recurso_id'), table_name='alocacao_recurso_projeto')
    op.drop_index(op.f('ix_alocacao_recurso_projeto_projeto_id'), table_name='alocacao_recurso_projeto')
    op.drop_table('alocacao_recurso_projeto')
    op.drop_index(op.f('ix_recurso_matricula'), table_name='recurso')
    op.drop_index(op.f('ix_recurso_jira_user_id'), table_name='recurso')
    op.drop_index(op.f('ix_recurso_equipe_principal_id'), table_name='recurso')
    op.drop_index(op.f('ix_recurso_email'), table_name='recurso')
    op.drop_table('recurso')
    op.drop_index(op.f('ix_projeto_status_projeto'), table_name='projeto')
    op.drop_index(op.f('ix_projeto_jira_project_key'), table_name='projeto')
    op.drop_index(op.f('ix_projeto_codigo_empresa'), table_name='projeto')
    op.drop_table('projeto')
    op.drop_index(op.f('ix_equipe_secao_id'), table_name='equipe')
    op.drop_table('equipe')
    op.drop_table('status_projeto')
    op.drop_table('secao')
    op.drop_table('dim_tempo')
    op.drop_table('configuracao')
    # ### end Alembic commands ### 